spring:
  application:
    name: springtest
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:spring_test_db}
    username: ${DB_USER:spring_test_user}
    password: ${DB_PASSWORD:spring_test_password}
    driver-class-name: org.mariadb.jdbc.Driver
server:
  error:
    include-message: always
